# Generated by Django 4.2.7 on 2024-12-15 09:09

from django.db import migrations, models
import kpi_tracker.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_login", models.DateTimeField(null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("azure_id", models.CharField(max_length=255, null=True, unique=True)),
                ("email", models.CharField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "[datahub].[KPI_Users]",
                "permissions": [
                    ("view_breast_kpi", "Can view Breast Cancer KPIs"),
                    ("edit_breast_kpi", "Can edit Breast Cancer KPIs"),
                    ("view_analytics", "Can view Analytics"),
                    ("admin_access", "Has admin access"),
                ],
                "managed": False,
            },
            managers=[
                ("objects", kpi_tracker.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BreastKPI",
            fields=[
                (
                    "MRN",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("CNC_name", models.CharField(blank=True, max_length=100, null=True)),
                ("Screening_date", models.DateField(blank=True, null=True)),
                ("Insurance_date", models.DateField(blank=True, null=True)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("", "----"), ("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("Age", models.IntegerField(blank=True, null=True)),
                (
                    "Nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----"),
                            ("Jordanian", "Jordanian"),
                            ("Non Jordanian", "Non Jordanian"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Patient_on_CPG",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "----"),
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Special cause", "Special cause"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "CPG_No",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("Palliative", "Palliative"),
                            (
                                "Patient refused treatment plan",
                                "Patient refused treatment plan",
                            ),
                            (
                                "Patient was started out KHCC non-standardized treatment protocol & can't continue as KHCC guidelines",
                                "Patient was started out KHCC non-standardized treatment protocol & can't continue as KHCC guidelines",
                            ),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "CPG_Special_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("Benign", "Benign"),
                            ("No show before treatment", "No show before treatment"),
                            ("Death before treatment", "Death before treatment"),
                            ("Second opinion", "Second opinion"),
                            (
                                "Referred for specific treatment",
                                "Referred for specific treatment",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("MDT_date", models.DateField(blank=True, null=True)),
                ("Treatment_date", models.DateField(blank=True, null=True)),
                (
                    "Treatment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("NeoAdjuvant CTx", "NeoAdjuvant CTx"),
                            ("Adjuvant CTx", "Adjuvant CTx"),
                            ("Surgery", "Surgery"),
                            ("Chemotherapy", "Chemotherapy"),
                            ("Chemo-radiotherapy", "Chemo-radiotherapy"),
                            ("Radiotherapy", "Radiotherapy"),
                            ("Hormonal", "Hormonal"),
                            ("Palliative", "Palliative"),
                            ("Palliative chemotherapy", "Palliative chemotherapy"),
                            ("None", "None"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "Reason_for_the_delay",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            (
                                "Not fit for starting treatment",
                                "Not fit for starting treatment",
                            ),
                            (
                                "Need more screening investigation",
                                "Need more screening investigation",
                            ),
                            ("Pathology delay", "Pathology delay"),
                            ("Admission list", "Admission list"),
                            ("Radiotherapy list", "Radiotherapy list"),
                            ("Chemotherapy list", "Chemotherapy list"),
                            ("Surgery list", "Surgery list"),
                            ("Financial issues", "Financial issues"),
                            ("COVID issues", "COVID issues"),
                            ("Miss her appointment", "Miss her appointment"),
                            ("Need more time to think", "Need more time to think"),
                            ("Patient related", "Patient related"),
                            (
                                "Delay on referral or clearance to other non-oncology services clinic",
                                "Delay on referral or clearance",
                            ),
                            (
                                "Delay on referral to other oncology services",
                                "Delay on referral to oncology",
                            ),
                            (
                                "Missed follow up from clinic",
                                "Missed follow up from clinic",
                            ),
                            (
                                "Patient ready and not discussed in MDC",
                                "Patient ready and not discussed in MDC",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Need_more_screening_investigation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("2nd look scan", "2nd look scan"),
                            ("Need another scan", "Need another scan"),
                            ("Need biopsy", "Need biopsy"),
                            ("Need Echo", "Need Echo"),
                            ("Genetic test delay", "Genetic test delay"),
                            ("Fertility issues", "Fertility issues"),
                            ("More consultations", "More consultations"),
                            ("Endocrine clearance", "Endocrine clearance"),
                            ("Pulmonary clearance", "Pulmonary clearance"),
                            (
                                "Abnormal laboratory findings",
                                "Abnormal laboratory findings",
                            ),
                            (
                                "Tumor marker processing time",
                                "Tumor marker processing time",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Treatment_NotFitForThisKPI", models.BooleanField(default=False)),
                (
                    "Neoadju_Bfr_Surgery",
                    models.CharField(
                        blank=True,
                        choices=[("", "----"), ("Yes", "Yes"), ("No", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("Neoadjuvant_ctx_date", models.DateField(blank=True, null=True)),
                ("Surgery_date", models.DateField(blank=True, null=True)),
                ("Surgeryneo_Delay_why", models.TextField(blank=True, null=True)),
                ("Surgery_NotFitForThisKPI", models.BooleanField(default=False)),
                (
                    "Adjuvant_radiotherapy",
                    models.CharField(
                        blank=True,
                        choices=[("", "----"), ("Yes", "Yes"), ("No", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "surgery_last_dose_adjuvant_chemotherapy_date",
                    models.DateField(blank=True, null=True),
                ),
                ("Radio_date", models.DateField(blank=True, null=True)),
                (
                    "Rdio_delay_why",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            (
                                "Not fit to start radiotherapy",
                                "Not fit to start radiotherapy",
                            ),
                            ("Patient related", "Patient related"),
                            ("Clinic appointment list", "Clinic appointment list"),
                            ("Miss her appointment", "Miss her appointment"),
                            ("COVID issues", "COVID issues"),
                            ("Review pathology report", "Review pathology report"),
                            ("Radiotherapy list", "Radiotherapy list"),
                            ("Need more time to think", "Need more time to think"),
                            ("Surgical issues", "Surgical issues"),
                            ("Insurance issues", "Insurance issues"),
                            ("Cardio clearance", "Cardio clearance"),
                            ("Delay in referral", "Delay in referral"),
                            ("Need more investigation", "Need more investigation"),
                            ("Patient refuse", "Patient refuse"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Radio_NotFitForThisKPI", models.BooleanField(default=False)),
                ("Pending", models.BooleanField(default=True)),
                (
                    "Oncologist_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Surgeon_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Radiotherapist_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("entry_ts", models.DateTimeField(auto_now_add=True)),
                ("last_update_ts", models.DateTimeField(auto_now=True)),
                ("Last_Follow_up_Date", models.DateField(blank=True, null=True)),
                ("Next_Follow_up_Date", models.DateField(blank=True, null=True)),
                ("Followup_remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "[datahub].[KPI_TblBreast]",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KPIActivityLog",
            fields=[
                ("log_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("SourcePage", models.CharField(max_length=50)),
                ("UserName", models.CharField(max_length=100)),
                ("UserEmail", models.CharField(max_length=100)),
                ("UserID", models.CharField(max_length=100)),
                ("MRN", models.CharField(max_length=50)),
                ("ts", models.DateTimeField()),
                ("Type", models.CharField(max_length=50)),
                ("Pending_Status", models.BooleanField()),
            ],
            options={
                "db_table": "[datahub].[KPI_ActivityLog]",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Physicians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Disease", models.CharField(max_length=50)),
                ("Physician_type", models.CharField(max_length=50)),
                ("Physician_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "[datahub].[KPI_TblPhysicians]",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "[datahub].[KPI_Users_Groups]",
                "managed": False,
            },
        ),
    ]
